In [9]:
import cv2 as cv
import numpy as np

In [10]:
img = cv.imread('img/opencvlogo.png')

In [11]:
print(img.shape)

(986, 800, 3)


In [12]:
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

In [13]:
print(gray.shape)

(986, 800)


In [17]:
gray = np.float32(gray)
print(gray)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [14]:
cv.imshow('gray', gray)

In [15]:
cv.waitKey(0)
cv.destroyAllWindows()