In [8]:
import cv2 as cv 
import numpy as np

In [9]:
image = cv.imread('../img/coins_filled.jpg',0 ) # görüntü okundu ve gri tonlamaya çevrildi
thresh, image2 = cv.threshold(image, 0, 255, cv.THRESH_BINARY + cv.THRESH_OTSU)

In [10]:
numlabels, labels, stats, centroids = cv.connectedComponentsWithStats(image2) # bağlantılı bileşenler bulundu

In [11]:
print('Toplam nesne sayısı:', numlabels-1) # arkaplanı da saydığı için 1 çıkarıldı
print('Nesnelerin özellikleri:', stats)
print('Nesnelerin ağırlık merkezleri:', centroids)

Toplam nesne sayısı: 10
Nesnelerin özellikleri: [[    0     0   300   246 50664]
 [  119     6    58    55  2509]
 [   31    26    50    47  1854]
 [  187    42    59    56  2538]
 [   85    61    49    47  1810]
 [    7    78    60    56  2650]
 [  240    78    50    48  1863]
 [  145    91    59    56  2592]
 [   66   117    60    57  2678]
 [  210   149    51    48  1891]
 [   90   179    60    58  2751]]
Nesnelerin ağırlık merkezleri: [[152.92365388 127.76827728]
 [147.54842567  33.44838581]
 [ 55.14509169  48.86245955]
 [215.92592593  69.80299448]
 [109.05966851  83.9281768 ]
 [ 36.14075472 105.72150943]
 [264.80944713 101.6129898 ]
 [173.83024691 118.98032407]
 [ 95.21396565 145.08364451]
 [235.06768905 172.35854045]
 [119.35405307 207.68338786]]


In [12]:
image_bgr = np.zeros((image.shape[0], image.shape[1], 3), dtype=np.uint8) # renkli görüntü oluşturuldu
image_bgr[:,:,0] = image_bgr[:,:,1] = image_bgr[:,:,2] = image # gri tonlamalı görüntü renkliye çevrildi

In [13]:
for i in range(1, numlabels):
    x, y, w, h, area = stats[i]
    cv.rectangle(image_bgr, (x, y), (x+w, y+h), (0, 255, 0), 2) # nesnelerin etrafına dikdörtgen çizildi
    cv.putText(image_bgr, str(i), (x, y), cv.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2) # nesnelerin üzerine etiket yazıldı
    


In [14]:
cv.imshow('original', image)
cv.imshow('1.görüntü:', np.uint8(labels==1)*255)
cv.imshow('2.görüntü:', np.uint8(labels==2)*255)
cv.imshow('Görüntü', image_bgr) 

cv.waitKey(0)
cv.destroyAllWindows()